Fix pool error handling
When an error is emitted by the pool, before pg-promise received the
client, the error handling failed with:

> TypeError: Cannot read property 'options' of undefined

Instead of handling pool error events separately, rely on them being
forwarded to the current connection attempt / query.